 const jsonData = [
  {
    end_year: "",
    intensity: 6,
    sector: "Energy",
    topic: "gas",
    insight: "Annual Energy Outlook",
    url: "http://www.eia.gov/outlooks/aeo/pdf/0383(2017).pdf",
    region: "Northern America",
    start_year: "",
    impact: "",
    added: "January, 20 2017 03:51:25",
    published: "January, 09 2017 00:00:00",
    country: "United States of America",
    relevance: 2,
    pestle: "Industries",
    source: "EIA",
    title:
      "U.S. natural gas consumption is expected to increase during much of the projection period.",
    likelihood: 3,
  },
    {
    end_year: 2021,
    intensity: 16,
    sector: "",
    topic: "",
    insight: "Short-term positives mask structural economic deficiencies",
    url: "http://country.eiu.com/article.aspx?articleid=1334864117&Country=Pakistan&topic=Economy",
    region: "",
    start_year: 2016,
    impact: "",
    added: "December, 02 2016 03:24:09",
    published: "November, 30 2016 00:00:00",
    country: "",
    relevance: 4,
    pestle: "",
    source: "EIU",
    title:
      "Price of Brent crude will average just US$60.5/b a year in 2017-21.",
    likelihood: 4,
  },
  {
    end_year: "",
    intensity: 6,
    sector: "Energy",
    topic: "consumption",
    insight: "Trudeau's Six Unanswered Questions on Kinder Morgan Expansion",
    url: "http://www.resilience.org/stories/2016-11-30/trudeau-s-six-unanswered-questions-on-kinder-morgan-expansion",
    region: "Eastern Asia",
    start_year: "",
    impact: "",
    added: "December, 02 2016 02:31:44",
    published: "November, 30 2016 00:00:00",
    country: "Japan",
    relevance: 2,
    pestle: "Industries",
    source: "Resilience",
    title:
      "Petroleum consumption in California, Japan and South Korea will decline.",
    likelihood: 3,
  },
  {
    end_year: 2020,
    intensity: 16,
    sector: "Construction",
    topic: "energy",
    insight:
      "UN: Paris Agreement still not good enough to avoid serious climate change",
    url: "http://www.edie.net/news/9/UN-Global-climate-action-must-scale-up-to-prevent-avoidable-human-tragedy/",
    region: "",
    start_year: "",
    impact: "",
    added: "December, 01 2016 15:34:33",
    published: "November, 03 2016 00:00:00",
    country: "",
    relevance: 4,
    pestle: "Industries",
    source: "edie.net",
    title:
      "All new buildings in OECD countries member countries will need to be zero-energy by 2020 to make the building sector compatible with the 1.5C warming target of COP21.",
    likelihood: 4,
  },
  {
    end_year: "",
    intensity: 6,
    sector: "Energy",
    topic: "oil",
    insight: "Oil price surges as Opec agrees first cut in output since 2008",
    url: "https://www.theguardian.com/business/2016/nov/30/oil-price-opec-cut-in-output-saudi-arabia-deal-market",
    region: "World",
    start_year: "",
    impact: "",
    added: "December, 01 2016 12:58:37",
    published: "November, 30 2016 00:00:00",
    country: "",
    relevance: 2,
    pestle: "Industries",
    source: "Guardian",
    title: "Global oil production will still be at a historically high level.",
    likelihood: 3,
  },
  {
    end_year: "",
    intensity: 4,
    sector: "Environment",
    topic: "aquaculture",
    insight:
      "Cargill developing new canola with long-chain omega-3-rich Canola to increase availability of nutritious fish",
    url: "http://www.cargill.com/news/releases/2016/NA31990270.jsp",
    region: "",
    start_year: "",
    impact: "",
    added: "December, 01 2016 03:32:37",
    published: "November, 28 2016 00:00:00",
    country: "",
    relevance: 2,
    pestle: "Environmental",
    source: "cargill",
    title:
      "A new groundbreaking type of canola in development by Cargill could give aquaculture farmers a more sustainable way to raise fish with EPA/DHA omega-3 fatty acids.",
    likelihood: 2,
  },
  {
    end_year: "",
    intensity: 6,
    sector: "Energy",
    topic: "oil",
    insight: "Can water go extinct?",
    url: "https://worldlyir.wordpress.com/2016/11/30/can-water-go-extinct/",
    region: "World",
    start_year: "",
    impact: "",
    added: "December, 01 2016 00:50:48",
    published: "November, 30 2016 00:00:00",
    country: "",
    relevance: 2,
    pestle: "Economic",
    source: "Worldly",
    title:
      "Prime Minister Justin Trudeau approved two more major pipeline projects in British Columbia that will vastly expand the amount of oil transported from the Alberta Tar Sands to global markets.",
    likelihood: 3,
  },
  {
    end_year: "",
    intensity: 9,
    sector: "Retail",
    topic: "export",
    insight: "Canada approves controversial Kinder Morgan oil pipeline",
    url: "https://www.theguardian.com/world/2016/nov/29/canada-approves-kinder-morgan-oil-pipeline-justin-trudeau?CMP=twt_gu",
    region: "Asia",
    start_year: "",
    impact: "",
    added: "November, 30 2016 02:59:41",
    published: "November, 30 2016 00:00:00",
    country: "United States of America",
    relevance: 3,
    pestle: "Economic",
    source: "Guardian",
    title:
      "Allowing Kinder Morgan to build a second pipeline next to its existing Trans Mountain line in Canada will help ensure oil exports reach Asia and reduce reliance on the US market.",
    likelihood: 3,
  },
  {
    end_year: "",
    intensity: 16,
    sector: "Energy",
    topic: "oil",
    insight: "Saudis believe Trump will unleash America's economy",
    url: "http://money.cnn.com/2016/11/28/investing/saudi-trump-oil-opec-meeting/index.html",
    region: "",
    start_year: 2017,
    impact: "",
    added: "November, 30 2016 00:34:59",
    published: "November, 28 2016 00:00:00",
    country: "",
    relevance: 4,
    pestle: "Industries",
    source: "CNNMoney",
    title:
      "There will be more thirst for oil in 2017 and oil prices will stabilize without OPEC intervention.",
    likelihood: 4,
  },
  {
    end_year: "",
    intensity: 6,
    sector: "Energy",
    topic: "oil",
    insight: "Get ready for $40 oil if OPEC deal collapses",
    url: "http://money.cnn.com/2016/11/28/investing/opec-meeting-oil-prices-saudi-iran/index.html",
    region: "",
    start_year: "",
    impact: "",
    added: "November, 30 2016 00:34:48",
    published: "November, 28 2016 00:00:00",
    country: "",
    relevance: 3,
    pestle: "Industries",
    source: "CNNMoney",
    title:
      "If a large cut is announced, oil prices could soar to $55 a barrel or higher.",
    likelihood: 2,
  },
  {
    end_year: "",
    intensity: 4,
    sector: "Energy",
    topic: "technology",
    insight:
      "Washington carbon capture project says it has permanently sequestered CO2",
    url: "http://www.utilitydive.com/news/washington-carbon-capture-project-says-it-has-permanently-sequestered-co2/430935/",
    region: "",
    start_year: "",
    impact: "",
    added: "November, 29 2016 02:16:47",
    published: "November, 22 2016 00:00:00",
    country: "",
    relevance: 2,
    pestle: "Technological",
    source: "Utility Dive",
    title:
      "Carbon capture is considered an expensive technology and the possibility of making it more secure and affordable could be a boon to coal-fired plants.",
    likelihood: 2,
  },
  {
    end_year: "",
    intensity: 12,
    sector: "",
    topic: "",
    insight: "Gamechangers",
    url: "https://www.gamechangers.newscientist.com/wp-content/uploads/2016/02/NSGamechangers.pdf",
    region: "Northern America",
    start_year: 2020,
    impact: "",
    added: "November, 28 2016 01:20:58",
    published: "February, 25 2016 00:00:00",
    country: "United States of America",
    relevance: 3,
    pestle: "",
    source: "newscientist",
    title:
      "If oil prices stay below $50 a barrel, US producers will pump out 2.5 million fewer barrels per day in 2020.",
    likelihood: 4,
  },
  {
    end_year: 2020,
    intensity: 12,
    sector: "Energy",
    topic: "biofuel",
    insight: "Gamechangers",
    url: "https://www.gamechangers.newscientist.com/wp-content/uploads/2016/02/NSGamechangers.pdf",
    region: "",
    start_year: "",
    impact: "",
    added: "November, 28 2016 01:20:56",
    published: "February, 25 2016 00:00:00",
    country: "",
    relevance: 3,
    pestle: "Political",
    source: "newscientist",
    title:
      "Biofuels will stall at about 4 percent of motor fuels through 2020.",
    likelihood: 4,
  },
  {
    end_year: "",
    intensity: 4,
    sector: "Energy",
    topic: "oil",
    insight: "Palm oil/Vegoils: Market factors to watch Monday Nov 7",
    url: "http://www.thestar.com.my/business/business-news/2016/11/07/palm-oil-market-factors-to-watch-nov-7/",
    region: "Southern Asia",
    start_year: "",
    impact: "",
    added: "November, 27 2016 07:01:47",
    published: "November, 07 2016 00:00:00",
    country: "Iran",
    relevance: 2,
    pestle: "Industries",
    source: "the star online",
    title: "Saudis could raise oil output again as sparring with Iran returns.",
    likelihood: 2,
  },
 ];
